name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Install Newman HTML Reporter
        run: npm install -g newman-reporter-html

      - name: Run Postman Tests with HTML Report
        run: |
          newman run postman-collection/Restful_Booker_API.postman_collection.json \
            -e postman-collection/Restful_BA_Env.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export postman-report.html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4  # ✅ UPDATED to v4
        with:
          name: postman-html-report
          path: postman-report.html
